
run_name: "eit"
artifact_root: "runs"
seed: 10086

problem:
  type: "eit"
  train_data: "./data/eit/train_withData_EIT.mat"
  test_data: "./data/eit/test_EIT.mat"

training:
  epochs: 2000
  batch_size: 100
  epoch_show: 100

  loss_weights:
    pde: 1.0
    data: 1.0
  optimizer:
    type: Adam
    lr: 0.0005
    weight_decay: 0.0001
  scheduler:
    type: StepLR
    step_size: 200
    gamma: 0.5
  nf:
    mode: separate
    epochs: 2000
    batch_size: 320
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.0
    scheduler:
      type: StepLR
      step_size: 400
      gamma: 0.333
