% Generates piecewise constant Darcy flow datasets for IGNO training.
%
% Coefficient fields are binary {k_low, k_high}, generated by thresholding
% a Gaussian Random Field with covariance (-Delta + tau^2 * I)^{-2}.
%
% Output .mat files (v7.3 / HDF5) contain:
%   coe  - (29, 29, N) piecewise constant coefficient fields
%   u    - (29, 29, N) PDE solutions on 29x29 grid
%   X, Y - (29, 29) meshgrid coordinates on [0,1]^2
%
% PDE: -div(k * grad(u)) = 10, u=0 on boundary, domain [0,1]^2
%
% Usage:
%   Edit k_low, k_high, and output_dir below, then run.
%   To generate all three datasets, call the script 3 times with different params,
%   or use: generate_darcy_piecewise(5, 10), generate_darcy_piecewise(5, 100), etc.
%   if you refactor into a function.
%
% The script generates 3 files per run:
%   pwc_train_data10000.mat  - 10000 in-distribution training samples (tau=3)
%   pwc_test_in.mat          -   200 in-distribution test samples     (tau=3)
%   pwc_test_out.mat         -   200 out-of-distribution test samples (tau=4)

clear; clc;

%% ===== PARAMETERS — edit these =====
k_low  = 5;
k_high = 1000;     % Change to 100 or 1000 for other contrast levels

% Path relative to project root (parent of scripts/)
script_dir = fileparts(mfilename('fullpath'));
output_dir = fullfile(script_dir, '..', 'data', sprintf('darcy_piecewise_5v%d', k_high));

N_train  = 10000;
N_test   = 200;

res_coe = 29;
nx_fem  = 64;   % FEM mesh resolution per side (64x64 nodes)

% GRF: covariance (-Delta + tau^2 * I)^{-2}
tau_in  = 3;    % in-distribution  (tau^2 = 9)
tau_out = 4;    % out-of-distribution (tau^2 = 16)

% Random seeds (fixed for reproducibility)
seed_train    = 1;
seed_test_in  = 2;
seed_test_out = 3;
%% =====================================

fprintf('=== Darcy Piecewise Dataset Generation ===\n');
fprintf('  k_low=%g, k_high=%g\n', k_low, k_high);
fprintf('  Output: %s\n\n', output_dir);

%% Build FEM mesh (reused for all samples)
fprintf('Building FEM mesh (%dx%d = %d nodes)...\n', nx_fem, nx_fem, nx_fem^2);
[xg, yg] = meshgrid(linspace(0,1,nx_fem), linspace(0,1,nx_fem));
nodes = [xg(:), yg(:)];
DT = delaunayTriangulation(nodes);
elems = DT.ConnectivityList;
n_nodes = size(nodes, 1);
n_elem  = size(elems, 1);
fprintf('  %d elements\n', n_elem);

% Boundary nodes (Dirichlet u=0)
tol_bdy = 1e-10;
bdy   = find(nodes(:,1) < tol_bdy | nodes(:,1) > 1-tol_bdy | ...
             nodes(:,2) < tol_bdy | nodes(:,2) > 1-tol_bdy);
free  = setdiff((1:n_nodes)', bdy);

% Precompute load vector (constant source f=10, never changes)
f_load = assemble_load_fast(nodes, elems);

% Element centers (for coefficient lookup, precomputed once)
elem_cx = (nodes(elems(:,1),1) + nodes(elems(:,2),1) + nodes(elems(:,3),1)) / 3;
elem_cy = (nodes(elems(:,1),2) + nodes(elems(:,2),2) + nodes(elems(:,3),2)) / 3;

% Output grid (29x29 on [0,1]^2)
[X, Y] = meshgrid(linspace(0,1,res_coe), linspace(0,1,res_coe));

% scatteredInterpolant — build once, update values in loop
F_interp = scatteredInterpolant(nodes(:,1), nodes(:,2), zeros(n_nodes,1), ...
                                'linear', 'linear');

if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

tic_total = tic;

fprintf('\nGenerating training data    (N=%5d, tau=%g, seed=%d)...\n', N_train, tau_in, seed_train);
[coe_train, u_train] = gen_samples(N_train, k_low, k_high, res_coe, ...
    nodes, elems, free, f_load, elem_cx, elem_cy, X, Y, F_interp, ...
    tau_in, seed_train);

fprintf('Generating in-dist test     (N=%5d, tau=%g, seed=%d)...\n', N_test, tau_in, seed_test_in);
[coe_test_in, u_test_in] = gen_samples(N_test, k_low, k_high, res_coe, ...
    nodes, elems, free, f_load, elem_cx, elem_cy, X, Y, F_interp, ...
    tau_in, seed_test_in);

fprintf('Generating out-of-dist test (N=%5d, tau=%g, seed=%d)...\n', N_test, tau_out, seed_test_out);
[coe_test_out, u_test_out] = gen_samples(N_test, k_low, k_high, res_coe, ...
    nodes, elems, free, f_load, elem_cx, elem_cy, X, Y, F_interp, ...
    tau_out, seed_test_out);

fprintf('\nTotal generation time: %.1f s\n', toc(tic_total));

fprintf('\nSaving to %s...\n', output_dir);

save_file(fullfile(output_dir, 'pwc_train_data10000.mat'), coe_train, u_train, X, Y);
save_file(fullfile(output_dir, 'pwc_test_in.mat'),         coe_test_in,  u_test_in,  X, Y);
save_file(fullfile(output_dir, 'pwc_test_out.mat'),        coe_test_out, u_test_out, X, Y);

fprintf('Done.\n');

% Quick sanity check
fprintf('\n=== Sanity check (training set) ===\n');
fprintf('  coe unique values: '); disp(unique(coe_train(:))');
fprintf('  u   range: [%.4f, %.4f]\n', min(u_train(:)), max(u_train(:)));
fprintf('  u   mean:   %.4f\n', mean(u_train(:)));


%% =============================================================
%% LOCAL HELPER FUNCTIONS
%% =============================================================

function [coe_all, u_all] = gen_samples(N, k_low, k_high, res_coe, ...
        nodes, elems, free, f_load, elem_cx, elem_cy, X, Y, F_interp, ...
        tau, seed)
    rng(seed);
    n_nodes = size(nodes, 1);
    coe_all = zeros(res_coe, res_coe, N, 'single');
    u_all   = zeros(res_coe, res_coe, N, 'single');

    K_free_cache = [];

    t_start = tic;
    for n = 1:N
        if mod(n, 1000) == 0
            elapsed = toc(t_start);
            fprintf('  [%5d/%5d]  %.1f s elapsed, ~%.1f s remaining\n', ...
                n, N, elapsed, elapsed/n*(N-n));
        end

        % 1. Sample GRF on res_coe x res_coe grid
        grf = sample_grf(res_coe, tau^2, 2);

        % 2. Threshold → binary coefficient field
        coe = k_low * ones(res_coe, res_coe);
        coe(grf > 0) = k_high;
        coe_all(:, :, n) = single(coe);

        % 3. Nearest-neighbor lookup: assign conductivity to FEM elements
        sigma = lookup_coe(elem_cx, elem_cy, coe, res_coe);

        % 4. Assemble stiffness matrix and solve
        K = assemble_stiffness_fast(nodes, elems, sigma);
        u_fem = zeros(n_nodes, 1);
        u_fem(free) = K(free, free) \ f_load(free);

        % 5. Interpolate FEM solution to output 29x29 grid
        F_interp.Values = u_fem;
        u_all(:, :, n) = single(F_interp(X, Y));
    end
end


function grf = sample_grf(N, tau_sq, alpha)
    % Sample one realization from GP(0, (-Δ + tau_sq * I)^{-alpha}) on [0,1]^2.
    % Spectral (FFT) method on N x N periodic grid.
    %
    % Only the sign is used (for thresholding), so normalization doesn't matter.
    %
    % tau_sq = 9  → in-distribution  (matches GP covariance from paper)
    % tau_sq = 16 → out-of-distribution
    % alpha  = 2  → smoothness exponent

    % Frequency grid in MATLAB FFT order: [0,1,...,N/2,-N/2+1,...,-1]
    k = [0 : floor(N/2), -floor((N-1)/2) : -1];
    [kx, ky] = meshgrid(k, k);

    % Square root of covariance eigenvalues: (4π²|k|² + τ²)^{-α/2}
    spectral_mult = (4 * pi^2 * (kx.^2 + ky.^2) + tau_sq) .^ (-alpha/2);
    spectral_mult(1,1) = 0;  % zero mean

    W = randn(N, N) + 1i * randn(N, N);
    grf = real(ifft2(spectral_mult .* W));
end


function sigma = lookup_coe(ex, ey, coe, res)
    % Nearest-neighbor lookup: map element centers (ex, ey) to coefficient values.
    % coe(i,j) = coefficient where i=row=y-direction, j=col=x-direction.
    % Matches fun_a() in the classical_method scripts.
    loc_x = min(max(floor(ex * (res-1) + 0.5) + 1, 1), res);
    loc_y = min(max(floor(ey * (res-1) + 0.5) + 1, 1), res);
    sigma = coe(sub2ind([res, res], loc_y, loc_x));
end


function K = assemble_stiffness_fast(nodes, elems, sigma)
    % Vectorized P1 FEM stiffness matrix assembly.
    % No element loop — assembles all entries at once via sparse().
    n_nodes = size(nodes, 1);
    i1 = elems(:,1);  i2 = elems(:,2);  i3 = elems(:,3);

    x1 = nodes(i1,1);  y1 = nodes(i1,2);
    x2 = nodes(i2,1);  y2 = nodes(i2,2);
    x3 = nodes(i3,1);  y3 = nodes(i3,2);

    % Element areas (positive by construction for Delaunay)
    area = 0.5 * abs((x2-x1).*(y3-y1) - (x3-x1).*(y2-y1));

    % Gradients of linear basis functions (per element)
    dN1dx = (y2 - y3) ./ (2*area);  dN1dy = (x3 - x2) ./ (2*area);
    dN2dx = (y3 - y1) ./ (2*area);  dN2dy = (x1 - x3) ./ (2*area);
    dN3dx = (y1 - y2) ./ (2*area);  dN3dy = (x2 - x1) ./ (2*area);

    % Element stiffness entries: k_ab = sigma * (grad_Na . grad_Nb) * area
    s = sigma .* area;
    k11 = s .* (dN1dx.*dN1dx + dN1dy.*dN1dy);
    k12 = s .* (dN1dx.*dN2dx + dN1dy.*dN2dy);
    k13 = s .* (dN1dx.*dN3dx + dN1dy.*dN3dy);
    k22 = s .* (dN2dx.*dN2dx + dN2dy.*dN2dy);
    k23 = s .* (dN2dx.*dN3dx + dN2dy.*dN3dy);
    k33 = s .* (dN3dx.*dN3dx + dN3dy.*dN3dy);

    rows = [i1;i1;i1; i2;i2;i2; i3;i3;i3];
    cols = [i1;i2;i3; i1;i2;i3; i1;i2;i3];
    vals = [k11;k12;k13; k12;k22;k23; k13;k23;k33];
    K = sparse(rows, cols, vals, n_nodes, n_nodes);
end


function f = assemble_load_fast(nodes, elems)
    % Vectorized load vector assembly for constant source f=10.
    n_nodes = size(nodes, 1);
    i1 = elems(:,1);  i2 = elems(:,2);  i3 = elems(:,3);

    x1 = nodes(i1,1);  y1 = nodes(i1,2);
    x2 = nodes(i2,1);  y2 = nodes(i2,2);
    x3 = nodes(i3,1);  y3 = nodes(i3,2);

    area = 0.5 * abs((x2-x1).*(y3-y1) - (x3-x1).*(y2-y1));
    fe = 10 * area / 3;  % f=10, distributed equally to 3 vertices

    f = accumarray([i1; i2; i3], [fe; fe; fe], [n_nodes, 1]);
end


function save_file(path, coe, u, X, Y)
    % Save dataset to HDF5-compatible .mat v7.3 file.
    %
    % MATLAB stores arrays in column-major order; Python's h5py reverses the
    % dimension order on read.  MATLAB [d1, d2, N] → Python (N, d2, d1).
    % The spatial dims d1,d2 are also swapped relative to MATLAB convention
    % (row=y, col=x).  We permute spatial dims before saving so that Python
    % reads coe/u as (N, y_idx, x_idx) — matching the original IGNO convention
    % and what get_high_res_a() expects.
    %
    % Same fix applied to X, Y: after permute + HDF5 reversal, X varies with
    % the second Python index (x-direction) as expected.
    coe = permute(coe, [2, 1, 3]);  % (res,res,N) → swap spatial dims
    u   = permute(u,   [2, 1, 3]);
    X   = X';
    Y   = Y';

    mb = (numel(coe) + numel(u)) * 4 / 1e6;
    fprintf('  Saving %s  [~%.0f MB]\n', path, mb);
    save(path, 'coe', 'u', 'X', 'Y', '-v7.3');
end
