run_name: darcy_piecewise_5v1000
artifact_root: runs
seed: 10086
problem:
  type: darcy_piecewise_5v1000
  train_data: ./data/darcy_piecewise_5v1000/pwc_train_data10000.mat
  test_data: ./data/darcy_piecewise_5v1000/pwc_test_in.mat
pretrained: null
training:
  epochs: 3000
  batch_size: 25
  epoch_show: 50
  loss_weights:
    pde: 1.0
    data: 1.0
    nf: 0.0
  optimizer:
    type: Adam
    lr: 0.0005
    weight_decay: 0.0001
  scheduler:
    type: StepLR
    step_size: 600
    gamma: 0.5
    eta_min: null
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0
  nf:
    mode: separate
    loss_weight: 1.0
    epochs: 4000
    batch_size: 128
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.0001
    scheduler:
      type: StepLR
      step_size: 800
      gamma: 0.333
      eta_min: null
      pct_start: 0.3
      div_factor: 25.0
      final_div_factor: 10000.0
evaluation:
  method: igno
  batch_size: 200
  n_obs: 100
  obs_sampling: random
  snr_db: null
  inversion:
    epochs: 500
    loss_weights:
      pde: 1.0
      data: 1.0
      nf: 1.0
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.0
    scheduler:
      type: null
      step_size: null
      gamma: null
      eta_min: null
      pct_start: 0.3
      div_factor: 25.0
      final_div_factor: 10000.0
  results_dir: results
